server:
      port: 9001
      
spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/microservice?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    
    